### PR TITLE
Retry CDI Read (when possible)

### LINKED ISSUE #42: Retry load datagram errors while fetching the CDI
If one of the datagrams for loading the CDI fails (for whaever reason, timeout, etc), we abort the load and return a partial XML for parsing -- which will always fail.
We should re-try the datagram load a few times before giving up.

### PR DESCRIPTION
**Pull request by bobjacobsen**
Will retry CDI reads that fail for several times before giving up. See #42

This retry doesn't always work, c.f. #128 where the datagram machine locks up.  But at least it will try now.

Closes #42

### CODE REVIEW

**Comment by bobjacobsen** [comment]
This is in use in JMRI now through a custom .jar file.  It would be good to get it merged before the end of May so that we can use a production .jar in the next production JMRI release.

File: src/org/openlcb/cdi/jdom/CdiMemConfigReader.java [hunk 1]
```diff
@@ -44,27 +44,37 @@ public CdiMemConfigReader(NodeID node, OlcbInterface iface, int space) {
...
+
+                int retryCount = 0;
+
                 @Override
                 public void handleFailure(int code) {
-                    logger.warning("Error reading CDI: " + Integer.toHexString(code));
-                    done();
-                    // TODO: 5/2/16 proxy error messages to the caller.
-                    // don't do next request
+                     // see if we can retry
```
Comment (balazsracz) [inline src/org/openlcb/cdi/jdom/CdiMemConfigReader.java:67]: We should check for the error code "read out of bounds". 
(I believe that's 0x1082: https://github.com/openlcb/documents/blob/master/standards/generated/MemoryConfigurationS.txt#L76 and https://github.com/openlcb/documents/blob/master/standards/generated/MessageNetworkS.txt#L375)

If the error that came back is out of bounds, then we don't need to re-try nor emit a warning, we are just done with the reads.
I guess we already do this in the memory tool when downloading a full memory space.

The way to test this is to have a memory space that's a multiple of 64 bytes long.

Comment (bobjacobsen) [reply src/org/openlcb/cdi/jdom/CdiMemConfigReader.java]: Done, thanks for pointing that out.

**Review by balazsracz — APPROVED** [review]
